# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timeseries.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='timeseries.proto',
  package='tutorial',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10timeseries.proto\x12\x08tutorial\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x03\n\x0eKafkaAiDataDto\x12#\n\x04tags\x18\x01 \x03(\x0b\x32\x15.tutorial.KafkaTagDto\x12\x0f\n\x07\x61lgCode\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65viceid\x18\x03 \x01(\t\x12\x0c\n\x04\x61iid\x18\x04 \x01(\t\x12\x12\n\ndevicename\x18\x05 \x01(\t\x12\x11\n\tparameter\x18\x06 \x01(\t\x12-\n\tstarttime\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x65ndtime\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x41\n\ralarm_configs\x18\t \x03(\x0b\x32*.tutorial.KafkaAiDataDto.AlarmConfigsEntry\x12\"\n\x04\x44\x61ta\x18\n \x03(\x0b\x32\x14.tutorial.DataDetail\x12\x0b\n\x03num\x18\x0b \x01(\x05\x12\x0e\n\x06maxnum\x18\x0c \x01(\x05\x1a\x44\n\x11\x41larmConfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.tutorial.Alarm:\x02\x38\x01\"(\n\nDataDetail\x12\x0c\n\x04time\x18\x01 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"N\n\x0bKafkaTagDto\x12\n\n\x02Id\x18\x01 \x01(\t\x12\x0c\n\x04\x41\x64\x64r\x18\x02 \x01(\t\x12\x11\n\tChannelId\x18\x03 \x01(\t\x12\x12\n\nSignalName\x18\x04 \x01(\t\"\x15\n\x05\x41larm\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_KAFKAAIDATADTO_ALARMCONFIGSENTRY = _descriptor.Descriptor(
  name='AlarmConfigsEntry',
  full_name='tutorial.KafkaAiDataDto.AlarmConfigsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tutorial.KafkaAiDataDto.AlarmConfigsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='tutorial.KafkaAiDataDto.AlarmConfigsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=499,
)

_KAFKAAIDATADTO = _descriptor.Descriptor(
  name='KafkaAiDataDto',
  full_name='tutorial.KafkaAiDataDto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tags', full_name='tutorial.KafkaAiDataDto.tags', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algCode', full_name='tutorial.KafkaAiDataDto.algCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviceid', full_name='tutorial.KafkaAiDataDto.deviceid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aiid', full_name='tutorial.KafkaAiDataDto.aiid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='devicename', full_name='tutorial.KafkaAiDataDto.devicename', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameter', full_name='tutorial.KafkaAiDataDto.parameter', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='starttime', full_name='tutorial.KafkaAiDataDto.starttime', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endtime', full_name='tutorial.KafkaAiDataDto.endtime', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alarm_configs', full_name='tutorial.KafkaAiDataDto.alarm_configs', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Data', full_name='tutorial.KafkaAiDataDto.Data', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='tutorial.KafkaAiDataDto.num', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxnum', full_name='tutorial.KafkaAiDataDto.maxnum', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_KAFKAAIDATADTO_ALARMCONFIGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=499,
)


_DATADETAIL = _descriptor.Descriptor(
  name='DataDetail',
  full_name='tutorial.DataDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='tutorial.DataDetail.time', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='tutorial.DataDetail.data', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=541,
)


_KAFKATAGDTO = _descriptor.Descriptor(
  name='KafkaTagDto',
  full_name='tutorial.KafkaTagDto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='tutorial.KafkaTagDto.Id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Addr', full_name='tutorial.KafkaTagDto.Addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ChannelId', full_name='tutorial.KafkaTagDto.ChannelId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SignalName', full_name='tutorial.KafkaTagDto.SignalName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=621,
)


_ALARM = _descriptor.Descriptor(
  name='Alarm',
  full_name='tutorial.Alarm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='tutorial.Alarm.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=644,
)

_KAFKAAIDATADTO_ALARMCONFIGSENTRY.fields_by_name['value'].message_type = _ALARM
_KAFKAAIDATADTO_ALARMCONFIGSENTRY.containing_type = _KAFKAAIDATADTO
_KAFKAAIDATADTO.fields_by_name['tags'].message_type = _KAFKATAGDTO
_KAFKAAIDATADTO.fields_by_name['starttime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_KAFKAAIDATADTO.fields_by_name['endtime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_KAFKAAIDATADTO.fields_by_name['alarm_configs'].message_type = _KAFKAAIDATADTO_ALARMCONFIGSENTRY
_KAFKAAIDATADTO.fields_by_name['Data'].message_type = _DATADETAIL
DESCRIPTOR.message_types_by_name['KafkaAiDataDto'] = _KAFKAAIDATADTO
DESCRIPTOR.message_types_by_name['DataDetail'] = _DATADETAIL
DESCRIPTOR.message_types_by_name['KafkaTagDto'] = _KAFKATAGDTO
DESCRIPTOR.message_types_by_name['Alarm'] = _ALARM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KafkaAiDataDto = _reflection.GeneratedProtocolMessageType('KafkaAiDataDto', (_message.Message,), {

  'AlarmConfigsEntry' : _reflection.GeneratedProtocolMessageType('AlarmConfigsEntry', (_message.Message,), {
    'DESCRIPTOR' : _KAFKAAIDATADTO_ALARMCONFIGSENTRY,
    '__module__' : 'timeseries_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.KafkaAiDataDto.AlarmConfigsEntry)
    })
  ,
  'DESCRIPTOR' : _KAFKAAIDATADTO,
  '__module__' : 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.KafkaAiDataDto)
  })
_sym_db.RegisterMessage(KafkaAiDataDto)
_sym_db.RegisterMessage(KafkaAiDataDto.AlarmConfigsEntry)

DataDetail = _reflection.GeneratedProtocolMessageType('DataDetail', (_message.Message,), {
  'DESCRIPTOR' : _DATADETAIL,
  '__module__' : 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.DataDetail)
  })
_sym_db.RegisterMessage(DataDetail)

KafkaTagDto = _reflection.GeneratedProtocolMessageType('KafkaTagDto', (_message.Message,), {
  'DESCRIPTOR' : _KAFKATAGDTO,
  '__module__' : 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.KafkaTagDto)
  })
_sym_db.RegisterMessage(KafkaTagDto)

Alarm = _reflection.GeneratedProtocolMessageType('Alarm', (_message.Message,), {
  'DESCRIPTOR' : _ALARM,
  '__module__' : 'timeseries_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Alarm)
  })
_sym_db.RegisterMessage(Alarm)


_KAFKAAIDATADTO_ALARMCONFIGSENTRY._options = None
# @@protoc_insertion_point(module_scope)
